#!/usr/bin/env python3
"""Generate/check the compiled SHA-256 manifest for curated runtime overrides."""
import argparse
import pathlib
import hashlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'common/3ds/InstallManifest.h'

def generate():
    lines = ['// Generated by scripts/tools/generate_install_manifest.py. Do not edit.',
             '#pragma once', 'namespace RegtaInstall {',
             'struct Entry { const char *path; unsigned size; unsigned char sha256[32]; };']
    for game in ('re3', 'revc', 'relcs'):
        lines.append('static const Entry %s[] = {' % game)
        base = ROOT / 'gamefiles' / game
        for path in sorted(base.rglob('*')):
            if not path.is_file() or path.name.startswith('.'):
                continue
            data = path.read_bytes()
            name = path.relative_to(base).as_posix()
            digest = ','.join('0x%02x' % byte for byte in hashlib.sha256(data).digest())
            lines.append('\t{"%s", %du, {%s}},' % (name, len(data), digest))
        lines.append('};')
    lines.append('}')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            raise SystemExit('Install manifest is stale. Run scripts/tools/generate_install_manifest.py.')
        print('Install manifest matches curated gamefiles.')
    else:
        OUTPUT.write_text(text)
